src/Entity/Media.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use App\Repository\MediaRepository;
use App\Validator\NoHtml;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: MediaRepository::class)]
#[ApiResource(
    operations: [
        new Get(),
        new GetCollection()
    ],
    normalizationContext: ['groups' => ['media:read']]
)]
class Media
{
    public const MEDIA_PER_PAGE = 10;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['theme:read', 'media:read', 'card:read'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['media:read', 'theme:read', 'card:read'])]
    #[NoHtml]
    private ?string $name = null;

    #[ORM\Column(length: 50)]
    #[Groups(['media:read', 'theme:read', 'card:read'])]
    private ?string $type = null;

    #[ORM\Column(name: "userGivenName", length: 255)]
    #[NoHtml]
    #[Groups(['theme:read', 'media:read', 'card:read'])]
    private ?string $userGivenName = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['media:read', 'card:read'])]
    private ?int $size = null;

    #[ORM\Column(length: 255)]
    #[Groups(['media:read', 'theme:read', 'card:read'])]
    private ?string $extensionFile = null;

    #[ORM\Column]
    #[Groups(['media:read', 'card:read'])]
    private ?\DateTimeImmutable $uploadedAt = null;

    /**
     * Cards qui utilisent ce média
     * Media est maintenant le côté INVERSE de la relation
     * @var Collection<int, Card>
     */
    #[ORM\ManyToMany(targetEntity: Card::class, mappedBy: 'medias')]
    #[Groups(['media:read'])]
    private Collection $cards;

    /**
     * @var Collection<int, Theme>
     */
    #[ORM\ManyToMany(targetEntity: Theme::class, inversedBy: 'medias')]
    #[ORM\JoinTable(name: 'media_theme')]
    #[Groups(['media:read'])]
    private Collection $themes;

    #[ORM\Column(nullable: true)]
    private ?bool $archived = null;

    public function __construct()
    {
        $this->cards = new ArrayCollection();
        $this->themes = new ArrayCollection();
        $this->uploadedAt = new \DateTimeImmutable();
        $this->archived = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getUserGivenName(): ?string
    {
        return $this->userGivenName;
    }

    public function setUserGivenName(string $userGivenName): static
    {
        $this->userGivenName = $userGivenName;

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(?int $size): static
    {
        $this->size = $size;

        return $this;
    }

    public function getExtensionFile(): ?string
    {
        return $this->extensionFile;
    }

    public function setExtensionFile(string $extensionFile): static
    {
        $this->extensionFile = $extensionFile;

        return $this;
    }

    public function getUploadedAt(): ?\DateTimeImmutable
    {
        return $this->uploadedAt;
    }

    public function setUploadedAt(\DateTimeImmutable $uploadedAt): static
    {
        $this->uploadedAt = $uploadedAt;

        return $this;
    }

    /**
     * @return Collection<int, Card>
     */
    public function getCards(): Collection
    {
        return $this->cards;
    }

    public function addCard(Card $card): static
    {
        if (!$this->cards->contains($card)) {
            $this->cards->add($card);
            $card->addMedia($this);
        }

        return $this;
    }

    public function removeCard(Card $card): static
    {
        if ($this->cards->removeElement($card)) {
            $card->removeMedia($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Theme>
     */
    public function getThemes(): Collection
    {
        return $this->themes;
    }

    public function addTheme(Theme $theme): static
    {
        if (!$this->themes->contains($theme)) {
            $this->themes->add($theme);
        }

        return $this;
    }

    public function removeTheme(Theme $theme): static
    {
        $this->themes->removeElement($theme);

        return $this;
    }

    /**
     * Retourne le chemin complet du fichier (relatif au dossier media)
     * Ex: "image/123.jpg"
     */
    public function getFilePath(): string
    {
        return $this->type . '/' . $this->name . '.' . $this->extensionFile;
    }

    /**
     * Retourne le nom complet du fichier avec extension
     * Ex: "123.jpg"
     */
    public function getFullFileName(): string
    {
        return $this->name . '.' . $this->extensionFile;
    }

    /**
     * Chemin public pour l'API (ex: /uploads/media/image/123.jpg)
     * Utilisable directement en React: REACT_API_URL + media.publicPath
     */
    #[Groups(['media:read', 'theme:read', 'card:read'])]
    public function getPublicPath(): ?string
    {
        if (!$this->name || !$this->type || !$this->extensionFile) {
            return null;
        }
        return sprintf('/uploads/media/%s/%s.%s', $this->type, $this->name, $this->extensionFile);
    }

    public function isArchived(): ?bool
    {
        return $this->archived;
    }

    public function setArchived(bool $archived): static
    {
        $this->archived = $archived;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Media;
use App\Entity\Theme;
use App\Form\ThemeType;
use App\Repository\ThemeRepository;
use App\Service\MediaUploader;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_USER')]
final class MainController extends AbstractController
{
    public function __construct(private readonly ThemeRepository        $themeRepository,
                                private readonly EntityManagerInterface $em,)
    {
    }

    #[Route('/', name: 'home')]
    #[Route('/{page<\d+>}', name: 'home_page', requirements: ['page' => '\d+'], methods: ['GET'])]
    public function home(int $page = 1): Response
    {
        $totalTheme = $this->themeRepository->count();
        $maxPages = ($totalTheme > 0) ? ceil($totalTheme / Theme::THEME_PER_PAGE) : 1;

        if ($page < 1) {
            return $this->redirectToRoute('home');
        }
        if ($page > $maxPages && $maxPages > 0) {
            return $this->redirectToRoute('home');
        }

        $paginator = $this->themeRepository->findALLWithPagination($page);
        $themes = iterator_to_array($paginator); // Ajoutez cette ligne

        return $this->render('main/home.html.twig', [
            'themes' => $themes,
            'currentPage' => $page,
            'maxPages' => $maxPages,
        ]);
    }


    #[Route('/theme/add', name: 'add_theme', methods: ['GET','POST'])]
    public function add(Request $request, MediaUploader $uploader): Response
    {
        $theme = new Theme();
        $formTheme = $this->createForm(ThemeType::class, $theme, [
            'is_admin' => $this->isGranted('ROLE_ADMIN')
        ]);
        $formTheme->handleRequest($request);

        if ($formTheme->isSubmitted() && $formTheme->isValid()) {
            try {
                $theme->setCreatedBy($this->getUser());

                // 1. Gérer l'image de fond principale
                $backgroundImageFile = $formTheme->get('backgroundImageFile')->getData();
                if ($backgroundImageFile) {
                    $media = new Media();

                    // IMPORTANT : Remplir les champs obligatoires AVANT le flush
                    $media->setUserGivenName($backgroundImageFile->getClientOriginalName());
                    $media->setName('temp'); // Temporaire, sera remplacé par l'ID
                    $media->setType('temp'); // Temporaire, sera détecté par l'uploader
                    $media->setExtensionFile('tmp'); // Temporaire, sera détecté par l'uploader

                    // Persister pour obtenir l'ID
                    $this->em->persist($media);
                    $this->em->flush();

                    // Upload le fichier (remplit name, type, extensionFile avec les vraies valeurs)
                    $uploader->upload($backgroundImageFile, $media);

                    // Associer au thème
                    $theme->setBackgroundImage($media);
                }

                // 2. Gérer les médias multiples
                $mediaFiles = $formTheme->get('mediaFiles')->getData();
                if ($mediaFiles) {
                    foreach ($mediaFiles as $file) {
                        $media = new Media();

                        // IMPORTANT : Remplir les champs obligatoires AVANT le flush
                        $media->setUserGivenName($file->getClientOriginalName());
                        $media->setName('temp'); // Temporaire, sera remplacé par l'ID
                        $media->setType('temp'); // Temporaire, sera détecté par l'uploader
                        $media->setExtensionFile('tmp'); // Temporaire, sera détecté par l'uploader

                        // Persister pour obtenir l'ID
                        $this->em->persist($media);
                        $this->em->flush();

                        // Upload le fichier (remplit name, type, extensionFile avec les vraies valeurs)
                        $uploader->upload($file, $media);

                        // Associer le média au thème
                        $theme->addMedia($media);
                    }
                }

                // 3. Sauvegarder le thème et tous les médias avec leurs vraies valeurs
                $this->em->persist($theme);
                $this->em->flush();

                $this->addFlash('success', 'Le thème ' . $theme->getName() . ' a bien été créé avec ses médias');
                return $this->redirectToRoute('home');

            } catch (\Exception $e) {
                $this->addFlash('error', 'Erreur lors de la création : ' . $e->getMessage());
            }
        }

        return $this->render('main/add_theme.html.twig', [
            'formTheme' => $formTheme,
        ]);
    }

    #[Route('/theme/edit/{id}', name: 'edit_theme', requirements: ['id' => '\d+'], methods: ['GET','POST'])]
    public function edit(Theme $theme, Request $request, MediaUploader $uploader): Response
    {
        if ($theme->isArchived()) {
            $this->addFlash('warning', 'Impossible de modifier un thème archivé.');
            return $this->redirectToRoute('home');
        }

        $formTheme = $this->createForm(ThemeType::class, $theme, [
            'is_admin' => $this->isGranted('ROLE_ADMIN')
        ]);
        $formTheme->handleRequest($request);

        if ($formTheme->isSubmitted() && $formTheme->isValid()) {
            try {
                // 1. Gérer l'image de fond principale
                $backgroundImageFile = $formTheme->get('backgroundImageFile')->getData();
                if ($backgroundImageFile) {
                    $media = new Media();

                    // IMPORTANT : Remplir les champs obligatoires AVANT le flush
                    $media->setUserGivenName($backgroundImageFile->getClientOriginalName());
                    $media->setName('temp'); // Temporaire, sera remplacé par l'ID
                    $media->setType('temp'); // Temporaire, sera détecté par l'uploader
                    $media->setExtensionFile('tmp'); // Temporaire, sera détecté par l'uploader

                    // Persister pour obtenir l'ID
                    $this->em->persist($media);
                    $this->em->flush();

                    // Upload le fichier (remplit name, type, extensionFile avec les vraies valeurs)
                    $uploader->upload($backgroundImageFile, $media);

                    // Associer au thème (remplace l'ancienne image)
                    $theme->setBackgroundImage($media);
                }

                // 2. Gérer les nouveaux médias multiples
                $mediaFiles = $formTheme->get('mediaFiles')->getData();
                if ($mediaFiles) {
                    foreach ($mediaFiles as $file) {
                        $media = new Media();

                        // IMPORTANT : Remplir les champs obligatoires AVANT le flush
                        $media->setUserGivenName($file->getClientOriginalName());
                        $media->setName('temp'); // Temporaire, sera remplacé par l'ID
                        $media->setType('temp'); // Temporaire, sera détecté par l'uploader
                        $media->setExtensionFile('tmp'); // Temporaire, sera détecté par l'uploader

                        // Persister pour obtenir l'ID
                        $this->em->persist($media);
                        $this->em->flush();

                        // Upload le fichier (remplit name, type, extensionFile avec les vraies valeurs)
                        $uploader->upload($file, $media);

                        // Ajouter le média au thème (s'ajoute aux existants)
                        $theme->addMedia($media);
                    }
                }

                // 3. Sauvegarder les modifications
                $this->em->flush();

                $this->addFlash('success', 'Thème ' . $theme->getName() . ' modifié avec succès !');
                return $this->redirectToRoute('home');

            } catch (\Exception $e) {
                $this->addFlash('error', 'Erreur lors de la modification : ' . $e->getMessage());
            }
        }

        return $this->render('main/edit_theme.html.twig', [
            'formTheme' => $formTheme,
            'theme' => $theme,
        ]);
    }


    #[Route('/theme/details/{id}', name: 'details_theme', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function details(int $id): Response
    {
        $theme = $this->themeRepository->findOneWithRelations($id);
        return $this->render('main/details_theme.html.twig', [
            'theme' => $theme,
        ]);
    }

    /**
     * Seul un admin est autorisé à supprimer un thème
     */
    #[Route('/theme/remove/{id}', name: 'remove_theme', requirements: ['id' => '\d+'], methods: ['POST'])]
    public function remove(Theme $theme): Response
    {
        $this->em->remove($theme);
        $this->em->flush();
        $this->addFlash('success', 'Thème '.$theme->getName().' bien supprimé.');
        return $this->redirectToRoute('home');
    }

    #[Route('/theme/archive/{id}', name: 'archive_theme', requirements: ['id' => '\d+'], methods: ['POST'])]
    public function archive(Theme $theme): Response
    {
        // Le ThemeArchiveListener va automatiquement archiver les cartes et médias liés
        $theme->setArchived(true);
        $this->em->persist($theme);
        $this->em->flush();

        $this->addFlash('success', 'Thème archivé avec succès (ainsi que ses cartes et médias).');
        return $this->redirectToRoute('admin_dashboard');
    }

    #[Route('/theme/un_archive/{id}', name: 'unarchive_theme', requirements: ['id' => '\d+'], methods: ['POST'])]
    public function unarchive(Theme $theme): Response
    {

templates/main/add_theme.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} | Création d'un theme{% endblock %}

{% block body %}
    {% embed 'views/form/form_template.html.twig' with {form : formTheme}%}
        {% block formTitle %} Creation d'un theme{% endblock %}
    {% endembed %}
{% endblock %}

templates/main/details_theme.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail de {{ theme.name }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="card">

            {# En-tête du thème #}
            <div class="theme-header">
                <h1>{{ theme.name }}</h1>
                <p class="theme-date">Créé le {{ theme.dateOfCreation|date('d/m/Y à H:i') }}</p>
                {% if theme.isArchived() %}
                    <p class="warning">Ce thème est archivé</p>
                {% endif %}
            </div>

            {# Image de fond du thème #}
            {% if theme.backgroundImage %}
                <div class="theme-section">
                    <h2>Image de fond</h2>
                    <div class="media-image-wrapper">
                        <img src="{{ asset('uploads/media/' ~ theme.backgroundImage.filePath) }}"
                             alt="Image de fond de {{ theme.name }}"
                             class="media-image-full">
                    </div>
                </div>
            {% endif %}

            {# Couleur de fond du thème #}
            {% if theme.themeBackgroundColor %}
                <div class="theme-section">
                    <h2>Couleur du thème</h2>
                    <div class="color-display">
                        <div class="color-pastille color-pastille-large" style="background-color: {{ theme.themeBackgroundColor.colorCode }};"></div>
                        <span class="color-code">{{ theme.themeBackgroundColor.colorCode }}</span>
                    </div>
                </div>
            {% endif %}

            {# Informations du thème #}
            <div class="theme-section">
                <div class="info-box">
                    <h2>Informations</h2>
                    <div class="info-grid">
                        <div class="info-item">
                            <strong>ID :</strong> {{ theme.id }}
                        </div>
                        {% if theme.createdBy %}
                            <div class="info-item">
                                <strong>Créé par :</strong> {{ theme.createdBy.username }}
                            </div>
                        {% endif %}
                        <div class="info-item">
                            <strong>Nombre de cartes :</strong> {{ theme.cards|length }}
                            <a href="{{ path('cards_add') }}"><button class="buttonCreate">Ajouter une Carte à ce thème</button></a>
                        </div>
                        <div class="info-item">
                            <strong>Nombre de médias :</strong> {{ theme.medias|length }}
                            <a href="{{ path('media_add') }}"><button class="buttonCreate">Ajouter un média à ce theme</button></a>
                        </div>
                    </div>
                </div>
            </div>

            {# Cartes liées au thème #}
            {% if theme.cards|length > 0 %}
                <div class="theme-section">
                    <h2>{{ theme.cards|length }} carte{{ theme.cards|length > 1 ? 's' : '' }} associée{{ theme.cards|length > 1 ? 's' : '' }}</h2>
                    <div class="cards-list">
                        {% for card in theme.cards %}
                            <div class="card-preview">
                                <h3>
                                    <a href="{{ path('cards_details', {'id': card.id}) }}">
                                        {{ card.title }}
                                    </a>
                                </h3>
                                {% if card.detail %}
                                    <p class="card-excerpt">
                                        {{ card.detail|slice(0, 150) }}{% if card.detail|length > 150 %}...{% endif %}
                                    </p>
                                {% endif %}
                                <div class="actions">
                                    <a href="{{ path('cards_details', {'id': card.id}) }}" class="btn buttonEdit">
                                        Voir détails
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                <div class="theme-section">
                    <div class="warning">
                        Aucune carte n'est encore associée à ce thème.
                    </div>
                </div>
            {% endif %}

            {# Médias liés au thème #}
            {% if theme.medias|length > 0 %}
                <div class="theme-section">
                    <h2>{{ theme.medias|length }} média{{ theme.medias|length > 1 ? 's' : '' }} associé{{ theme.medias|length > 1 ? 's' : '' }}</h2>
                    <div class="cards-list">
                        {% for media in theme.medias %}
                            <div class="card-preview">
                                {% if media.type == 'image' %}
                                    <div class="media-preview">
                                        <img src="{{ asset('uploads/media/' ~ media.filePath) }}"
                                             alt="{{ media.userGivenName }}"
                                             class="media-thumbnail">
                                    </div>
                                {% else %}
                                    <div class="media-placeholder">
                                        <p class="media-type-label">{{ media.type|upper }}</p>
                                    </div>
                                {% endif %}
                                <h3 class="media-title">{{ media.userGivenName }}</h3>
                                <p class="media-info">
                                    Type: {{ media.type|upper }} • {{ media.extensionFile|upper }}
                                </p>
                                <div class="actions">
                                    <a href="{{ path('media_detail', {'id': media.id}) }}" class="btn buttonEdit">
                                        Voir détails
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                <div class="theme-section">
                    <div class="warning">
                        Aucun média n'est encore associé à ce thème.
                    </div>
                </div>
            {% endif %}

            {# Actions #}
            <hr class="separator">

            <div class="ligne">
                {% if not theme.isArchived() %}
                    <a href="{{ path('edit_theme', {'id': theme.id}) }}" class="buttonEdit">
                        Modifier
                    </a>
                {% endif %}

                <a href="{{ path('home') }}" class="buttonEdit">
                    Retour à la liste
                </a>

                {% if is_granted('ROLE_ADMIN') %}
                    {% if not theme.archived %}
                        <a href="{{ path('archive_theme', {'id': theme.id}) }}"
                           class="buttonRemove"
                           onclick="return confirm('Êtes-vous sûr de vouloir archiver ce thème ? Toutes les cartes et médias associés seront également archivés.')">
                            Archiver
                        </a>
                    {% else %}
                        <a href="{{ path('unarchive_theme', {'id': theme.id}) }}"
                           class="buttonCreate"
                           onclick="return confirm('Êtes-vous sûr de vouloir désarchiver ce thème ?')">
                            Désarchiver
                        </a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/main/edit_theme.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} | Modification de {{ theme.name }}{% endblock %}

{% block body %}
    {% embed 'views/form/form_template.html.twig' with {form : formTheme}%}
        {% block formTitle %} Modifier le theme : {{ theme.name}} !{% endblock %}
    {% endembed %}
{% endblock %}

templates/main/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
    <h1>Gestion des données du musée des transmissions</h1>

    <a href="{{ path('add_theme') }}" class="buttonCreate">Créer un thème</a>

    {% if themes|length == 0 %}
        <div class="card">
            <p>Aucun thème disponible dans la base de données pour le moment.</p>
            <p>Commencez par créer votre premier thème !</p>
        </div>
    {% else %}
        <table>
            <thead>
            <tr>
                <th>Nom du thème</th>
                {% if is_granted('ROLE_ADMIN') %}
                    <th>Statut</th>
                    <th>Créé par</th>
                {% endif %}
                <th>Date de création</th>
                <th>Cartes</th>
                <th>Médias</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for theme in themes %}
                <tr {% if theme.isArchived() %}class="warning"{% endif %}>
                    <td>
                        <a href="{{ path('details_theme', {'id': theme.id}) }}">
                            {{ theme.name }}
                        </a>
                    </td>
                    {% if is_granted('ROLE_ADMIN') %}
                        <td>
                            {% if theme.isArchived() %}
                                Archivé
                            {% else %}
                                Actif
                            {% endif %}
                        </td>
                        <td>
                            {% if theme.createdBy %}
                                {{ theme.createdBy.username }}
                            {% else %}
                                <em>Non défini</em>
                            {% endif %}
                        </td>
                    {% endif %}
                    <td>{{ theme.dateOfCreation|date('d/m/Y') }}</td>
                    <td>{{ theme.cards|length }}</td>
                    <td>{{ theme.medias|length }}</td>
                    <td class="ligne">
                        <a href="{{ path('details_theme', {'id': theme.id}) }}" class="buttonEdit">Voir</a>
                        {% if not theme.isArchived() %}
                            <a href="{{ path('edit_theme', {'id': theme.id}) }}" class="buttonEdit">Modifier</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {# Pagination #}
        {% if maxPages > 1 %}
            <div class="ligne">
                {# Page précédente #}
                {% if currentPage > 1 %}
                    <a href="{{ path('home', {'page': currentPage - 1}) }}" class="buttonEdit">
                        Précédent
                    </a>
                {% endif %}

                {# Page suivante #}
                {% if currentPage < maxPages %}
                    <a href="{{ path('home', {'page': currentPage + 1}) }}" class="buttonEdit">
                        Suivant
                    </a>
                {% endif %}
            </div>
        {% endif %}
    {% endif %}
{% endblock %}